version: '3.8'

services:
  text-adventure:
    build:
      context: .
    stdin_open: true
    tty: true
    ports:
      - "3000:3000"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge